name: MasterHand Flutter CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  analyze_and_test:
    name: Lint & Testes Unitários
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.22.x"
          channel: "stable"
          cache: false # Desativado temporariamente para limpar o cache anterior
      - run: flutter pub get
      - run: dart run build_runner build
      - run: flutter analyze --fatal-infos
      - run: flutter test --coverage

  build_android:
    name: Build Android (APK)
    runs-on: ubuntu-latest
    needs: analyze_and_test
    steps:
      - uses: actions/checkout@v4
      
      # Garantindo o Java 17 explicitamente antes do Flutter
      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"
          
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.22.x"
          channel: "stable"
          cache: false # Desativado temporariamente para não trazer arquivos antigos quebrados
          
      - run: flutter pub get
      - run: dart run build_runner build
      
      # Comando adicionado para limpar qualquer resquício do Gradle antigo
      - name: Clean Gradle
        run: cd android && ./gradlew clean && cd ..
        
      - run: flutter build apk --release --no-shrink
      
      - uses: actions/upload-artifact@v4
        with:
          name: masterhand-android-apk
          path: build/app/outputs/flutter-apk/app-release.apk
          retention-days: 7